### ISSUE TITLE
Cheaper alternative parts

### ISSUE THREAD

**Issue by cendern** [Madelena/esphome-weatherman-dashboard#1]
Any idea whether the tri-color 7.5" screen from Waveshare would work? It's $59.95 which is about $9 cheaper on Amazon than the one you have linked. The difference is that it doesn't have the Raspberry Pi hat that I assume you wouldn't need since you're driving it with an ESP32.
https://www.amazon.com/dp/B076BVFHDV

There's also an even cheaper (but lower resolution) option for $53.99. I would guess the resolution difference wouldn't matter with this use case. Again not 100% sure about compatibility, but it's the same brand:
https://www.amazon.com/dp/B075R69T93

Also this driver which I think is the exact same part is a few bucks cheaper:
https://www.amazon.com/dp/B07RM1BBVF

I would have just PR'ed your readme but I can't create your affiliate links and I'm not 100% certain that the screens are drop-in replacements.

**Comment by Madelena** [comment]
> Any idea whether the tri-color 7.5" screen from Waveshare would work? It's $59.95 which is about $9 cheaper on Amazon than the one you have linked. The difference is that it doesn't have the Raspberry Pi hat that I assume you wouldn't need since you're driving it with an ESP32. https://www.amazon.com/dp/B076BVFHDV

This might work. The Pi hat is not needed. Note that tri-color screens refresh slower than monochrome screens, so you cannot really show sensors that require frequent updates per minute with it.

> There's also an even cheaper (but lower resolution) option for $53.99. I would guess the resolution difference wouldn't matter with this use case. Again not 100% sure about compatibility, but it's the same brand: https://www.amazon.com/dp/B075R69T93

Yes, this should also work, and yes it has a lower resolution.

> I would have just PR'ed your readme but I can't create your affiliate links and I'm not 100% certain that the screens are drop-in replacements.

Amazon rejected my affiliate link application anyway 😞 so I will need to switch back to normal links eventually.

**Comment by chunkysteveo** [comment]
Worth noting that ESPHome doesn's support colour/tri-colour e-paper displays - only black and white.
