### ISSUE TITLE
Display last updated time

### ISSUE THREAD

**Issue by Madelena** [Madelena/esphome-weatherman-dashboard#12]
Would be nice to see when the display was last refreshed.

**Comment by paviro** [comment]
I have this in my version can back port it here on the weekend.

**Comment by Madelena** [comment]
> I have this in my version can back port it here on the weekend.

That would be awesome! 😍

**Comment by paviro** [comment]
Done see #15.

**Comment by Madelena** [comment]
Also added to the display itself in the latest commit. :)
