### ISSUE TITLE
Missing '-' glyph for negative temperatures.

### ISSUE THREAD

**Issue by asthecryflows** [Madelena/esphome-weatherman-dashboard#13]
Simple change needed to weatherman.yaml - add '-' to the array of glyphs included with font_large_bold.

I feel like this should be somewhat trivial, but for the sake of making things more convenient for future users of this, I thought I'd mention it.

**Comment by Madelena** [comment]
Fixed! Thank you for reporting. New York has hit negative temperatures last month so this update is timely! 🥶
