### ISSUE TITLE
Great project - why the PNG titles?

### ISSUE THREAD

**Issue by chunkysteveo** [Madelena/esphome-weatherman-dashboard#2]
Love the project, looks great in the frame. I have a question though - why the use of PNG images for the text titles, and not using written text in the ESPHome display lambda?

**Comment by Madelena** [comment]
Good point. I did that when I first started because I wanted to try adding images and I didn't trust ESPHome's font rendering. But seeing how well the temperature is rendered, it makes sense not using a PNG at all.

**Comment by chunkysteveo** [comment]
Ahhh - cool! No worries! Was wondering just in case there was a rendering issue - but the temperature values look so good, I was curious. 

Thanks
