### ISSUE TITLE
Inverting White to Black Shows No Display

### ISSUE THREAD

**Issue by RichardD012** [Madelena/esphome-weatherman-dashboard#6]
I bought the same components as listed in the README and wanted black text/images on white background. I inverted everything and now I can see the black text painted but then it almost immediately gets replaced to where you can only see the ghosted image of it.

I'm not sure if you experienced any situation like this but I didn't know if it was a mis-mapping on the pins or something else was wrong but I can clearly see the correct information painted but if you use `color_white` instead of `color_black` and vice/versa, nothing gets displayed.

**Comment by RichardD012** [comment]
I may be off base here but switching the A/B pin on the driver board to A seems to have fixed "this". Any insight would be appreciated but leaving here if anyone experiences something similar.  It was sort of difficult to find the wave share documentation on this board as it doesn't seem to line up 1:1 with anything on their website.

**Comment by Madelena** [comment]
Let me investigate it and see what comes up.

**Comment by RichardD012** [comment]
For what it's worth, flipping the DIP switch seems to make the banding from your screenshots go away. I have zero idea if this is actually correct but that switching being in the A position makes the output super crisp.

**Comment by Bruhildo** [comment]
Hey @RichardD012 , could this be what you are looking for?

[Driver Board Wiki](https://www.waveshare.com/wiki/E-Paper_ESP32_Driver_Board)

There is a table detailing the use of switch A/B on the driver board under item: Preparation -> Hardware Connection ->

As I see, all 7.5' displays should be on A.

I got the white/black and red display and was considering including some artefacts in red, but could not get that far yet.

**Comment by RichardD012** [comment]
This was super helpful and exactly what I was looking for. I had been trying to track down the specific display settings and not going to the driver board which seems obvious in hindsight. 

Everything so far has been working great and this has been a huge help (including your links to the material design icon help for getting the icon codes).  I'll close this out and maybe someone can come across this in the future.
